development:
  twilio_account_sid: "ACb0a3e2a1933b587ddae7788edff01416"
  twilio_auth_token: "e31bd4ca269d3efd814eff738dcfa2f7"
  twilio_phone_number: "+15814814931"
  zendesk_api_key: ""
  SENDGRID_API_KEY: "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"
  google_map_api_key: "AIzaSyCYrqDV-0WJCpE5wSEPu3zpa7_G_LQ7naA"
  google_captcha: "6LeJEkcdAAAAAJ1ytjuQ-hsX8338YlNSO4gWD9Bq"
  ibm_watson_api_key: "XonmBszwvVddmK8DmLFOwEkGvfHnxGxkd-FpacGy22OR"
  ibm_watson_url: "https://api.us-east.text-to-speech.watson.cloud.ibm.com/instances/8e595f09-9d1d-4e80-8fdc-bda4592e6b75"
  blazer_db_url: "postgres://postgres:@localhost:5432/data_warehouse"
  open_weather_api_key: "314b5bf027667b8f225bca9a093bb144"
  DROPBOX_OAUTH_BEARER: "jPVAb3ntdacAAAAAAAAAAXrGJ_F5F-EoWNVH5IRQJqfMzR13b9wn2gFwjiPLMQuM"
  dropbox_id: "6qt741s5oj5qs2f"
  dropbox_secret: "462k6qi5j2hwqwc"
  machine_learning: "86ac445eb51243f78432e3b351b0f0ee"