default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  port: /var/run/mysqld/mysqld.sock

postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: marcalexandreperussecavanagh
  password:

primary:
  <<: *default
  database: Rocket_Elevators_Information_System_development

secondary:
  <<: *postgres
  database: data_warehouse
  migrations_paths: db/secondary_migrate

# secondbase:
#   development:
#     adapter: postgresql
#     database: Rocket_Elevators_Information_System_development

#   test:
#     adapter: postgresql
#     database: Rocket_Elevators_Information_System_test

  
development:
  <<: *default
  database: Rocket_Elevators_Information_System_development

production:
  <<: *default
  database: Rocket_Elevators_Information_System_production
  username: Rocket_Elevators_Information_System
  password: <%= ENV['ROCKET_ELEVATORS_INFORMATION_SYSTEM_DATABASE_PASSWORD'] %>




# default: &default
#   adapter: mysql2
#   encoding: utf8
#   username: codeboxx
#   password: Codeboxx1!
#   host: codeboxx.cq6zrczewpu2.us-east-1.rds.amazonaws.com
#   port: 3306


# postgres: &postgres
#   adapter: postgresql
#   encoding: utf8
#   username: codeboxx
#   password: Codeboxx1!
#   host: codeboxx-postgresql.cq6zrczewpu2.us-east-1.rds.amazonaws.com
#   port: 5432
# primary:
#   <<: *default
#   database: MARC_ALEXANDRE_PERUSSE_CAVANAGH
# secondary:
#   <<: *postgres
#   database: MARC_ALEXANDRE_PERUSSE_CAVANAGH
#   migrations_paths: db/secondary_migrate
# development:
#   <<: *default
#   database: MARC_ALEXANDRE_PERUSSE_CAVANAGH