default: &default
  adapter: mysql2
  encoding: utf8
  username: dbmasteruser
  password: Codeboxx1!
  host: ls-1c6447086c8b2894cde0dcfec2a51ae6f890d1ef.coojzbjc1mjk.ca-central-1.rds.amazonaws.com
  port : 3306


postgres: &postgres
  adapter: postgresql
  encoding: utf8
  username: dbmasteruser
  password: Codeboxx1!
  host: ls-452f0a759af81e4cb0e6a7e781c9f2d87f9626f8.coojzbjc1mjk.ca-central-1.rds.amazonaws.com
  port: 5432

primary:
  <<: *default
  database: RocketElevators
secondary:
  <<: *postgres
  database: RocketElevators
  migrations_paths: db/secondary_migrate

development:
    <<: *default
    database: RocketElevators